sudo: required

dist: trusty

os:
  - linux
  # - osx TODO re-enable osx support

go_import_path: github.com/ipfs/go-ipfs

language: go

go:
    - 1.5.2

before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

env:
  - TEST_VERBOSE=1 TEST_SUITE=test_go_expensive
  - TEST_VERBOSE=1 TEST_SUITE=test_sharness_expensive

script:
  - make $TEST_SUITE
